<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SharpInference.Graphs\SharpInference.Graphs.csproj" />
    <ProjectReference Include="..\SharpInference.Instructions\SharpInference.Instructions.csproj" />
  </ItemGroup>
</Project>
