<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\SharpInference.Abstractions\SharpInference.Abstractions.csproj" />
    <ProjectReference Include="..\SharpInference.Core\SharpInference.Core.csproj" />
    <ProjectReference Include="..\SharpInference.Models.Rwkv\SharpInference.Models.Rwkv.csproj" />
    <ProjectReference Include="..\SharpInference.Runtime\SharpInference.Runtime.csproj" />
    <ProjectReference Include="..\SharpInference.Applications\SharpInference.Applications.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\THIRD-PARTY-NOTICES.txt" Link="THIRD-PARTY-NOTICES.txt">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
