<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SharpInference.Abstractions\SharpInference.Abstractions.csproj" />
    <ProjectReference Include="..\SharpInference.Core\SharpInference.Core.csproj" />
    <ProjectReference Include="..\SharpInference.Generation\SharpInference.Generation.csproj" />
    <ProjectReference Include="..\SharpInference.Graphs\SharpInference.Graphs.csproj" />
    <ProjectReference Include="..\SharpInference.Models.Ggml\SharpInference.Models.Ggml.csproj" />
    <ProjectReference Include="..\SharpInference.Gguf\SharpInference.Gguf.csproj" />
    <ProjectReference Include="..\SharpInference.Vm\SharpInference.Vm.csproj" />
    <ProjectReference Include="..\SharpInference.Vm.Optimization\SharpInference.Vm.Optimization.csproj" />
    <ProjectReference Include="..\SharpInference.Instructions\SharpInference.Instructions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
